#! /usr/bin/env bash
. ~soft_bio_267/initializes/init_netanalyzer
. ~soft_bio_267/initializes/init_autoflow
execution_dir=`dirname $0`
CODE_PATH=$(readlink -f $execution_dir )
export PATH=$CODE_PATH'/scripts:'$PATH
# templates, scripts and initial_data folder is not generated by this sh

#############################################################################
## INPUT/OUTPUT
#############################################################################
ROOT_PATH=~/proyectos/kernel/full_testing/execution
NET_DATA_DOWN=$ROOT_PATH'/net_downloaded_data'
NET_DATA_PROC=$ROOT_PATH'/net_processed_data'
NET_DEF=$ROOT_PATH'/net_definitive_matrix'
EVALUATION=$ROOT_PATH'/kernel_evaluation'
FINAL_RESULTS=$ROOT_PATH'/final_results'

mkdir -p $NET_DATA_DOWN $NET_DATA_PROC $NET_DEF $EVALUATION $FINAL_RESULTS

#############################################################################
## DOWNLOAD DATA
#############################################################################
if [ "$1" == "d" ] ; then
	# NETWORK DATA
	#====================================================================

	# STRING
	#----------------
	wget 'https://stringdb-static.org/download/protein.links.full.v11.0/9606.protein.links.full.v11.0.txt.gz' -O $NET_DATA_DOWN'/string_data.txt.gz'
	wget 'https://string-db.org/mapping_files/entrez/human.entrez_2_string.2018.tsv.gz' -O $NET_DATA_DOWN'/string_id_mapping.tsv.gz'

	# OTHER
	#----------------

	# GOLD STANDARD
	#====================================================================

	# UNBIASED WAY
	#----------------
	wget http://string82.embl.de/newstring_download/protein.links.v8.2.txt.gz -O $NET_DATA_DOWN'/string_old.txt.gz'
	wget http://string82.embl.de/newstring_download/protein.aliases.v8.2.txt.gz -O $NET_DATA_DOWN'/string_old_aliases.txt.gz'

fi

#############################################################################
## PROCESS DATA
#############################################################################

if [ "$1" == "p" ] ; then
	# NETWORK DATA
	#====================================================================

	# STRING
	#----------------
	string_thresold=99
	gunzip -d $NET_DATA_DOWN'/string_data.txt.gz'
	gunzip -d $NET_DATA_DOWN'/string_id_mapping.tsv.gz'
	sed 's/9606\.//g' $NET_DATA_DOWN'/string_data.txt' -i
	tail -n +2 $NET_DATA_DOWN'/string_id_mapping.tsv' | cut -f 2,3 | sed 's/9606\.//g' > $NET_DATA_PROC/entrez2ensemblP
	tail -n +2 $NET_DATA_DOWN'/string_data.txt' | awk -F ' ' '{if($14 >= "'$string_thresold'") print $1 "\t" $2}' | text2binary_matrix.rb -i - -o $NET_DEF'/unw_StringTextmining_f'string_thresold'_bin'

	# GOLD STANDARD
	#====================================================================

	# CLASSIC EVALUATION
	#----------------------
	get_disease_classes.rb $CODE_PATH'/initial_data/diseasome_from_paper.tsv' 30 > $NET_DATA_PROC'/diseasome_classes'

	# UNBIASED WAY
	#---------------------
	# String data
	gunzip $NET_DATA_DOWN'/string_old.txt.gz'
	gunzip $NET_DATA_DOWN'/string_old_aliases.txt.gz'
	grep '9606\.' $NET_DATA_DOWN'/protein.links.v8.2.txt' | sed 's/9606\.//g' |tr ' ' '\t' > $NET_DATA_PROC'/human_interactions'
	text2binary_matrix.rb -i $NET_DATA_PROC'/human_interactions'  -o $NET_DATA_PROC'/unb_way_val_matrix_bin' -O bin
	awk '{if($1 == "9606" && $4 == "Ensembl" ) print $2 "\t" $3}' $NET_DATA_DOWN'/protein.aliases.v8.2.txt' | grep 'ENSG' > $NET_DATA_PROC'/proteinID2geneID'
	# Seed data
	unify_seed_files.rb -s $CODE_PATH'/initial_data/scuba_val_seed_groups' -o $NET_DATA_PROC'/scuba_val_seed_groups' -i $NET_DATA_PROC'/proteinID2geneID'

fi

#############################################################################
## LAUNCH WORKFLOW
#############################################################################
CLASSIC_EVAL=$EVALUATION'/evaluation_classic'
UNBIASED_EVAL=$EVALUATION'/evaluation_unbiased'

mkdir -p $CLASSIC_EVAL $UNBIASED_EVAL
TIME_RESOURCE='7-00:00:00'
#TIME_RESOURCE='01:00:00'
#MEMORY_RESOURCE='200gb'
MEMORY_RESOURCE='16gb'
#QUEUE='bigmem' # for 'el' kernel
QUEUE='cal'
ACTIVE_KERNELS='[ct;ka;el]'
if [ "$1" == "lc" ] ; then # Launch classic evaluation
	
	ls $NET_DEF | grep -v '.lst' > $EVALUATION'/working_mats'
	while read MATRIX
	do
	        variables=`echo -e "
			\\$scripts_path=$CODE_PATH'/scripts',
        	\\$working_mat=$MATRIX,
        	\\$mat_folder=$NET_DEF,
			\\$kernels2exec=$ACTIVE_KERNELS,
			\\$entrez2ensemblP=$NET_DATA_PROC/entrez2ensemblP,
            \\$diseasome_seeds=$NET_DATA_PROC'/diseasome_classes'
	        " | tr -d [:space:]`
		AutoFlow -w $CODE_PATH'/templates/classic_evaluation.af' -o $CLASSIC_EVAL'/'$MATRIX -V $variables $2 -m $MEMORY_RESOURCE -t $TIME_RESOURCE -n $QUEUE
	done < $EVALUATION'/working_mats'
elif [ "$1" == "lu" ] ; then # Launch unbiased way evaluation
        variables=`echo -e "
		\\$scripts_path=$CODE_PATH'/scripts',
       	\\$working_mat=unb_way_val_matrix_bin,
       	\\$mat_folder=$NET_DATA_PROC,
		\\$kernels2exec=$ACTIVE_KERNELS,
        \\$unbiased_group_seeds=$NET_DATA_PROC'/scuba_val_seed_groups'
        " | tr -d [:space:]`
	AutoFlow -w $CODE_PATH'/templates/unbiased_way_evaluation.af' -o $UNBIASED_EVAL'/old_string' -V $variables $2 -m $MEMORY_RESOURCE -t $TIME_RESOURCE -n $QUEUE
fi

#############################################################################
## COMPARE KERNEL RESULTS
#############################################################################

if [ "$1" == "c" ] ; then
	. ~soft_bio_267/initializes/init_report_html
	cat $CLASSIC_EVAL/*/metrics > $FINAL_RESULTS/classic_stats 
	create_metric_table.rb $FINAL_RESULTS/classic_stats Name,Source,Kernel $FINAL_RESULTS/classic_metric_table
	# cat $UNBIASED_EVAL/old_string/metrics > $FINAL_RESULTS/unbiased_stats
	# create_metric_table.rb $FINAL_RESULTS/unbiased_stats kernel $FINAL_RESULTS/unbiased_metric_table
	sed 's/StringTextmining/StTm/g' $FINAL_RESULTS/*_metric_table -i
	sed 's/_bin//g' $FINAL_RESULTS/*_metric_table -i
	
	paths=`echo -e "
	$FINAL_RESULTS/classic_metric_table
	" | tr -d [:space:]`

	report_html -t $CODE_PATH'/templates/general_report.erb' -d $paths -o $FINAL_RESULTS'/final_report'
fi
